### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by Nick-Mul** [sergio-santos-group/ProtoSyn.jl#42]
Hi guys, I really like this project and it looks a good excuses to learn a bit of julia. As set up is half the battle and I was wondering if you had got a good container recipes?

This is my "work in progress" but it's not got cuda working and the pycall isn't linking between python and julia.... 

FROM mambaorg/micromamba:0.24.0

RUN micromamba install -y --name base -c conda-forge numpy pytorch pip
RUN micromamba install -y --name base -c nvidia -c pytorch cudatoolkit=11.3
RUN micromamba install -y --name base -c conda-forge torchani libgcc

USER root
RUN apt-get update && apt-get install -y \
    apache2 \
    curl \
    git \
    python3-pip \
    vim \
    libstdc++6
RUN pip install julia jill
RUN jill install 1.6.2 --confirm

**Comment by JosePereiraUA** [comment]
Hey! We currently don't have such a docker recipe (yet), but this seems like a good start. A couple things:

- ProtoSyn has been tested mostly for the most recent Julia version (1.7.2+). It seems you're using pip to install Julia? This may work, but I'll just leave an alternative here:
```
wget https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz
tar zxvf julia-1.7.3-linux-x86_64.tar.gz
export PATH="$PATH:/path/to/<Julia directory>/bin"
```
- ProtoSyn doesn't "really" need CUDA. For small systems (up to 3000 atoms), most operations actually run faster in the CPU using the SIMD acceleration mode. ProtoSyn should automatically set this up when no CUDA is detected. You can manually change this too: `ProtoSyn.acceleration.active = ProtoSyn.SIMD_1` should do the trick.
- For linking Python with Julia (using PyCall), you should get a warning message prompting you to define the installation location of Python in an environment variable. I think you're supposed to open a new Julia prompt and do `ENV["PYTHON"] = "... path of the python executable ..."` and then `Pkg.build("PyCall")`. You can get more info [here](https://github.com/JuliaPy/PyCall.jl).
- I've never used `microbamba` but if that doesn't work, try installing `torchani` using `pip`. See the documentation [here](https://aiqm.github.io/torchani/start.html).
- I highly recommend you try out the [#dev](https://github.com/sergio-santos-group/ProtoSyn.jl/tree/dev) branch: the 1.0 release is now highly outdated - I'm actually finishing up on documentation and tests to release v1.1 over the next couple weeks!

Thank you for your support. Please remember this is an highly experimental package - bugs are to be expected, but hopefully, as more users start to explore ProtoSyn, we'll be able to iron them out! So yhea, fell free to post all problems you face when trying out ProtoSyn.

**Comment by Nick-Mul** [comment]
Thanks for your help! I am up and running. FYI Dockerfile was; 

FROM condaforge/mambaforge:latest

ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN conda update conda -c conda-forge
RUN conda update mamba -c conda-forge

RUN mamba create -n myenv -y -q pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch -c nvidia
RUN mamba install -y --name myenv -y -q -c conda-forge torchani


USER root
RUN apt-get update && apt-get install -y \
    apache2 \
    curl \
    git \
    python3-pip \
    vim \
    libstdc++6
RUN pip install julia jill


RUN jill install 1.7.2 --confirm

COPY assets/install.jl .
RUN julia install.jl

with the install script being .... 

using Pkg
packages = ["JSON", "CSV","PyCall"]
Pkg.add(packages)
ENV["PYTHON"]="/opt/conda/envs/myenv/bin/python"
Pkg.build("PyCall")
Pkg.add(url="https://github.com/FluxML/ONNX.jl")
Pkg.add(url="https://github.com/sergio-santos-group/ProtoSyn.jl.git")

**Comment by Nick-Mul** [comment]
Hi Jose, Sorry for bothering you. I got this error 

/opt/conda/envs/myenv/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
/opt/conda/envs/myenv/lib/python3.9/site-packages/torchani/resources/
ERROR: LoadError: MethodError: no method matching getindex(::Nothing, ::String)
Stacktrace:

have you a yaml file for your python environment you can share? 

Also say this ;)
https://discourse.julialang.org/t/equivalent-to-rosetta-in-julia/32168

**Comment by JosePereiraUA** [comment]
Hi!
You're not bothering at all ahah
First of all, I'll try to produce a yaml file for the conda environment, but that's a weird error: when installing torchani, everything should be installed. I'll look into it.

Secondly, thanks for the link! I'll leave a comment pointing people towards ProtoSyn.jl. It is not (and never will) be a replacement for Rosetta. It's more like a complement. A place where people can try out new algorithms and models (much like in Rosetta) but in a free open-source, well documented and easy to understand platform.

But yhea, we started development on ProtoSyn.jl because Rosetta was such a pain-in-the-*** to modify ahah

**Comment by JosePereiraUA** [comment]
I've added an experimental `protosyn.yml` conda environment file to the [#dev](https://github.com/sergio-santos-group/ProtoSyn.jl/tree/dev) branch.
However, for the error you showed, I managed to replicate it and solve it by installing ASE manually: [https://anaconda.org/conda-forge/ase](https://anaconda.org/conda-forge/ase).

```
conda install -c conda-forge ase
```

I'm still not sure (running some Travis CI builds) but I think the potential conda environment file must reflect each user's GPU card (and installed drivers, etc). Not sure how feasible is this: I'm completely over my head here ahah

**Comment by Nick-Mul** [comment]
Awesome! adding in
`  conda install -c conda-forge ase`
worked 👍  and I've started to work through your documentation, it maybe a learning curve I've never used Rosetta. Btw how does the graph format deal with ligands I often want to tweak a protein - ligand complex. Also good pyRosetta blog here https://blog.matteoferla.com/

**Comment by JosePereiraUA** [comment]
Nice, happy to help! And thanks for the blog post, I'll give it a look.

A couple of replies:

**1. What documentation are you reading?** The currently hosted documentation belongs to release 1.0, while the #dev branch is currently marked as release 1.1. I'm desperately trying to host the new documentation via Travis CI (and failing miserably at it, if you or someone who know has some experience with this sort of things, please, send help ahah). One option (for now) is to build and host the new documentation locally.

```
cd docs/
julia make.jl
python -m http.server
``` 

And pick the `build/` directory. This was you can read the new documentation in a neat presentation. As soon as I have the new documentation up and running online I'll let you know.

**2. On the peptide-ligand complex.** ProtoSyn's graph is hierarchically organized: a Topology is a set of Segments (i.e. continuous molecules of atoms), which in turn are sets of Residues (i.e. aminoacids, monomers), which, finally, are a set of Atoms. There's 2 graph levels: the main directional graph is at the Atom level (so atoms have parents and can have children), but there's also the level of organization at the residue level (residues can have parents and children). To start this graph, there's a virtual `root` Residue (with three `root` atoms), so every first atom in each Segment is a child of this system-wide `root`. In the case of a peptide-ligand complex, we would have 2 segments. As such, methods like `travel_graph!` (when starting on an atom of Segment A) will never apply changes to atoms of segment B. Does this make sense? I can try and explain it better if I was confusing.

**3. How do you work with dockers?** I've spent way too much time on this and still failed to understand the objetive of dockers. What are the commands you use to go from the Dockerfile to actual installations on your machine? Or isn't the purpose of Docker to "automatically" install dependencies, etc? I think I need a tutorial ahah

Anyways, hope you enjoy exploring ProtoSyn, please, keep sending bugs and questions!

**Comment by Nick-Mul** [comment]
Hi Jose, 

I am enjoying reading the files, it's an impressive body of work.

1. Thanks for the pointer, I am reading the right documentation now. I am afraid Travis Cl isn't something I've come across, I'll post it on one of my work's Yammer channel. 
2. Yes that makes sense. Thanks :)
3. Docker is an a way of having an clean, isolated machine with all the dependencies in place. It makes run the code on different machines really easy (M1/M2 chips are sometimes but not always a problem) . You often start from a base image 
`FROM nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu18.04`
and add the things you need
   `RUN apt update ; apt upgrade -y ; apt-get -y install build-essential git wget libboost-all-dev libeigen3-dev libgoogle-glog-dev libprotobuf-dev protobuf-compiler libhdf5-dev libatlas-base-dev python3-dev librdkit-dev python3-numpy python3-pip python3-pytest`

A good example is a colleague gave me some code to run all written in python but it was actually calling a linux package graphviz so didn't work on my machine. 

So Dockerfile is the recipe for a docker image, you then run an image to make a container. To build an image run the following command in the directory with the "Dockerfile" the -t tags the image with a name here julia_python
`docker build -t julia_python .` 
see what images are available locally with
`docker image list` 
then to run the container. 
`docker run -it --rm -v $PWD:$PWD -w $PWD localhost/julia_python bash`
-v is [volume ](https://docs.docker.com/storage/volumes/) where the data is written to access from. -it interactive -rm automatically clean up the container and remove the file system when the container exits. -w is the working directory.   "localhost/julia_python" is the image name. then finally bash at the end to interact with the container.  Lots of other ways to run it too for example you can use docker to run a jupyter notebook with Julia installed. jupyter/datascience-notebook has Julia installed. https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
