### ISSUE TITLE
Issue applying a new Rotamer to the sidechains

### ISSUE THREAD

**Issue by Nick-Mul** [sergio-santos-group/ProtoSyn.jl#45]
FYI in example 3 molecular manipulations, I was having problems with the ProtoSyn.Peptides.phi part of this line phi = ProtoSyn.getdihedral(pose.state, ProtoSyn.Peptides.phi(pose.graph[1][4])) 

 Version      : 1.01

**Comment by JosePereiraUA** [comment]
I've recently changed the code (and the examples), make sure you're using the latest #dev commit.
I can run the example fine:
![image](https://user-images.githubusercontent.com/31994358/177053882-a2e5716d-f8e7-43a8-b955-af28a7e520d2.png)

If the problem persists, let me know. Sorry for the unstable state, I'm planning on releasing a more stable version ASAP.

**Comment by Nick-Mul** [comment]
Sorry yes that's all working for me know, I wasn't on the dev branch! Thanks 👍
